kind: CronJob
apiVersion: batch/v1
metadata:
  name: minute-backup
  namespace: nginx
spec:
  schedule: "* * * * *"
  jobTemplate: 
    spec:
      template:
        metadata:
          name: minute-backup
          labels:
            app: minute-backup
        
        spec:
          containers:
          - name: backup-container
            image: busybox:latest
            command:
            - sh
            - -c
            - |
              echo "Backup started at $(date)"
              sleep 5
              echo "Backup completed"
          restartPolicy: OnFailure